apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-validator-registration-contract
spec:
  template:
    spec:
      priorityClassName: best-effort-priority
      containers:
      - name: deployer
        image: gcr.io/prysmaticlabs/prysm/contracts/vrc/deployer:latest
        args: 
          - "--httpPath=http://$(GETH_NODES_SERVICE_HOST):$(GETH_NODES_SERVICE_PORT_RPC)"
          - "--privKey=783da8ef5343c3019748506305d400bca8c324a5819f3a7f7fbf0c0a0d799b09"
        resources:
          requests:
            memory: "50Mi"
            cpu: "25m"
          limits:
            memory: "100Mi"
            cpu: "100m"
      restartPolicy: Never
  backoffLimit: 2