apiVersion: batch/v1
kind: Job
metadata:
  name: deploy-validator-registration-contract
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - --httpPath=http://$(GETH_NODES_SERVICE_HOST):$(GETH_NODES_SERVICE_PORT_RPC)
        - --privKey=783da8ef5343c3019748506305d400bca8c324a5819f3a7f7fbf0c0a0d799b09
        image: gcr.io/prysmaticlabs/prysm/contracts/vrc/deployer@sha256:86557ada20c1f9b40e60b6626418f76950649059ea3e3b873baeeb3dabd80654
        name: deployer
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 25m
            memory: 50Mi
      priorityClassName: best-effort-priority
      restartPolicy: Never