kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: beacon-chain
spec:
  replicas: 3
  selector:
    matchLabels:
      component: beacon-chain
      universe: beacon-chain
  template:
    metadata:
      labels:
        component: beacon-chain
        universe: beacon-chain
    spec:
      priorityClassName: production-priority
      containers:
        - name: beacon-chain
          image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
          args: 
            - "--web3provider=ws://$(GETH_NODES_SERVICE_HOST):$(GETH_NODES_SERVICE_PORT_WS)"
            - "--verbosity=debug"
            - "--pubkey=0x0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
            - "--vrcaddr=0x541AfaC5266c534de039B4A1a53519e76ea82846"
            - "--rpc-port=4000"
            - "--simulator=false"
            - "--validator"
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "100m"
          ports:
            - containerPort: 4000
              name: grpc
