kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: proposer
spec:
  replicas: 3
  selector:
    matchLabels:
      component: proposer
      universe: client
  template:
    metadata:
      labels:
        component: proposer
        universe: client
    spec:
      priorityClassName: batch-priority
      containers:
        - name: sharding-client
          image: gcr.io/prysmaticlabs/prysm/client:latest
          args: 
            - "--rpc=http://$(GETH_NODES_SERVICE_HOST):$(GETH_NODES_SERVICE_PORT_RPC)"
            - "--actor=proposer"
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "100m"
