kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: validator
spec:
  replicas: 3
  selector:
    matchLabels:
      component: validator
      universe: client
  template:
    metadata:
      labels:
        component: validator
        universe: client
    spec:
      priorityClassName: batch-priority
      containers:
        - name: sharding-validator
          image: gcr.io/prysmaticlabs/prysm/validator:latest
          args: 
            - "--beacon-rpc-provider=http://$(BEACON_CHAIN_SERVICE_HOST):$(BEACON_CHAIN_SERVICE_PORT_GRPC)"
            - "--verbosity=debug"
          resources:
            requests:
              memory: "100Mi"
              cpu: "50m"
            limits:
              memory: "250Mi"
              cpu: "100m"
